spring:
    application:
        name: discovery
    redis:
        host: localhost
        port: 6379

server:
    port: 8761
 
# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
    instance:
        hostname: localhost
    client:
        region: default
        registryFetchIntervalSeconds: 5
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://discUser:discPassword@localhost:8761/eureka/
    

    