spring:
    application:
        name: gateway
    redis:
        host: localhost
        port: 6379

server:
    port: 8080
 
# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
    instance:
        hostname: localhost
    client:
        region: default
        registryFetchIntervalSeconds: 5
        
       
zuul:
    routes:
        discovery:
            path: /discovery/**
            sensitive-headers: Set-Cookie,Authorization
            url: http://localhost:8761/api/discovery/
            
hystrix:
    command:
        discovery:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 600000
 
 
management:
    security:
        sessions :always