server:
    port: 8761
    context-path: /discovery

spring:
    redis:
        host: localhost
        port: 6379
 
# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
    instance:
        hostname: localhost
        
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://discUser:discPassword@${eureka.instance.hostname}:${server.port}/eureka/
    



