spring:
  aop:
    proxyTargetClass: true
  

server:
    port: 8765
 
eureka:
    client:
        serviceUrl:
             defaultZone: http://localhost:8761/eureka/


zuul:
  debug:
    request: true
  routes:
    uaa:
      sensitiveHeaders:
      path: /uaa/**
      stripPrefix: false
  add-proxy-headers: true
  
security:
  # Disable Spring Boot basic authentication
  basic:
    enabled: false
  oauth2:
    sso:
      loginPath: /uua/login
    client:
      accessTokenUri: http://localhost:${server.port}/uaa/oauth/token
      userAuthorizationUri: /uua/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      jwt:
        keyValue: |
            -----BEGIN PUBLIC KEY-----
            MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDNQZKqTlO/+2b4ZdhqGJzGBDlt
            b5PZmBz1ALN2YLvt341pH6i5mO1V9cX5Ty1LM70fKfnIoYUP4KCE33dPnC7LkUwE
            /myh1zM6m8cbL5cYFPyP099thbVxzJkjHWqywvQih/qOOjliomKbM9pxG8Z1dB26
            hL9dSAZuA8xExjlPmQIDAQAB
            -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource

logging:
  level.org.springframework.security: DEBUG


