server:
    port: 8765

spring:
    application:
        name: gateway
    redis:
        host: localhost
        port: 6379
 
eureka:
    client:
        region: default
        registryFetchIntervalSeconds: 5
        
zuul:
  routes: 
    uaa-service:
      sensitiveHeaders: Set-Cookie,Authorization
      path: /uaa/**
    discovery-service:
      sensitiveHeaders: Set-Cookie,Authorization
      path: /discovery/**
      url: http://localhost:8761
      

management:
  security:
      sessions: always

hystrix:
  command:
      uaa-service:
          execution:
              isolation:
                  thread:
                      timeoutInMilliseconds: 600000
      discovery:
          execution:
              isolation:
                  thread:
                      timeoutInMilliseconds: 600000

 
logging:
  level.org.springframework.security: DEBUG


