server:
    port: 0
    context-path: /uaa
    use-forward-headers: false
 
eureka:
   client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

spring:
    redis:
        host: localhost
        port: 6379

logging:
  level.org.springframework.security: DEBUG


