server:
    port: 0
    
 
eureka:
   client:
        region: default
        registryFetchIntervalSeconds: 5


spring:
    application:
        name: uaa
    redis:
        host: localhost
        port: 6379


management:
    security:
        sessions: never

logging:
  level.org.springframework.security: DEBUG


