server:
    port: 0
    
 
eureka:
   client:
        region: default
        registryFetchIntervalSeconds: 5

pocketmoney:
    database: hsqldb
        
spring:
    application:
        name: user-service
    datasource:
        schema: classpath*:db/${pocketmoney.database}/schema.sql
        data: classpath*:db/${pocketmoney.database}/data.sql
    jpa:
        hibernate:
            ddl-auto: non

            
management:
    security:
        enabled: false
            
logging:
    level:
        org:
            springframework:INFO
               


